menu:
    Blog: /
    Archive: /archives/
    Tags: /tags/
    Rss: /atom.xml
    GitHub: https://github.com/fancxxy
    Weibo: https://www.weibo.com/fancxxy

favicon: favicon.ico
logo: logo.gif #https://avatars2.githubusercontent.com/u/7724598?s=466&v=3

# Comment
# e.g disqus: seansun
disqus: fancxxy
# duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2018
